import { Schema, model } from 'mongoose';

const GameSchema = new Schema({
  roomId: { type: String, required: true, min: 2 },
  playerOne : { type: String, default: ''},
  playerTwo : { type: String, default: ''},
  gameData: { type: Object, default:'', fields:{
    currentMove: { type: Number, required: true },
    stage: { type: Number, default: 0 },
    store: {
      wheat_field: { type: Number, required: true },
      ranch: { type: Number, required: true },
      bakery: { type: Number, required: true },
      cafe: { type: Number, required: true },
      convenience_store: { type: Number, required: true },
      forest: { type: Number, required: true },
      tv_station: { type: Number, required: true },
      publisher: { type: Number, required: true },
      cheese_factory: { type: Number, required: true },
      furniture_factory: { type: Number, required: true },
      tax_office: { type: Number, required: true },
      mine: { type: Number, required: true },
      family_restaraunt: { type: Number, required: true },
      apple_orchard: { type: Number, required: true },
      fruit_and_vegetable_market: { type: Number, required: true },
      train_station: { type: Number, required: true },
      shopping_mall: { type: Number, required: true },
      amusement_park: { type: Number, required: true },
      radio_tower: { type: Number, required: true },
      city_hall: { type: Number, required: true },
    },
    players: {
      1: {
        properties: {
          city_hall: { type: Number, required: true },
          cafe: { type: Number, required: true },
          family_restaraunt: { type: Number, required: true },
          wheat_field: { type: Number, required: true },
          ranch: { type: Number, required: true },
          bakery: { type: Number, required: true },
          convenience_store: { type: Number, required: true },
          forest: { type: Number, required: true },
          cheese_factory: { type: Number, required: true },
          furniture_factory: { type: Number, required: true },
          mine: { type: Number, required: true },
          apple_orchard: { type: Number, required: true },
          fruit_and_vegetable_market: { type: Number, required: true },
          tv_station: { type: Number, required: true },
          publisher: { type: Number, required: true },
          tax_office: { type: Number, required: true },
          train_station: { type: Number, required: true },
          shopping_mall: { type: Number, required: true },
          amusement_park: { type: Number, required: true },
          radio_tower: { type: Number, required: true },
        },
        money: { type: Number, required: true },
        money_to_earn: { type: Number, required: true },
      },
      2: {
        properties: {
          city_hall: { type: Number, required: true },
          cafe: { type: Number, required: true },
          family_restaraunt: { type: Number, required: true },
          wheat_field: { type: Number, required: true },
          ranch: { type: Number, required: true },
          bakery: { type: Number, required: true },
          convenience_store: { type: Number, required: true },
          forest: { type: Number, required: true },
          cheese_factory: { type: Number, required: true },
          furniture_factory: { type: Number, required: true },
          mine: { type: Number, required: true },
          apple_orchard: { type: Number, required: true },
          fruit_and_vegetable_market: { type: Number, required: true },
          tv_station: { type: Number, required: true },
          publisher: { type: Number, required: true },
          tax_office: { type: Number, required: true },
          train_station: { type: Number, required: true },
          shopping_mall: { type: Number, required: true },
          amusement_park: { type: Number, required: true },
          radio_tower: { type: Number, required: true },
        },
        money: { type: Number, required: true },
        money_to_earn: { type: Number, required: true },
      },
    }}
  },
});

export const GameModel = model('Game', GameSchema, 'Games');
